import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const mainContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

const canvasContext = await esbuild.context({
	entryPoints: ["canvas.tsx"],
	bundle: true,
	format: "iife",
	platform: "browser",
	target: "es2018",
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
	logLevel: "info",
	loader: {
		".css": "text",
	},
	outfile: "canvas.bundle.js",
	minify: prod,
});

if (prod) {
	await mainContext.rebuild();
	await canvasContext.rebuild();
	process.exit(0);
} else {
	await mainContext.watch();
	await canvasContext.watch();
}
